drop table if exists public.site_settings;

create table public.site_settings (
  id bigint generated by default as identity primary key,
  whatsapp_number text,
  booking_message text,
  email_address text,
  social_facebook_url text,
  social_instagram_url text,
  social_tiktok_url text,
  physical_address text,
  copyright_year integer,
  inserted_at timestamptz default now(),
  updated_at timestamptz default now()
);

insert into public.site_settings (
  id,
  whatsapp_number,
  booking_message,
  email_address,
  social_facebook_url,
  social_instagram_url,
  social_tiktok_url,
  physical_address,
  copyright_year
) values (
  1,
  '+6281234567890',
  'Hello, can I get more detail about this package?',
  'admin@balitravel.com',
  'https://facebook.com/bali',
  'https://instagram.com/bali',
  'https://www.tiktok.com/@balivoy',
  'Jln mertasari indah no 140',
  2023
)
on conflict (id) do update set
  whatsapp_number = excluded.whatsapp_number,
  booking_message = excluded.booking_message,
  email_address = excluded.email_address,
  social_facebook_url = excluded.social_facebook_url,
  social_instagram_url = excluded.social_instagram_url,
  social_tiktok_url = excluded.social_tiktok_url,
  physical_address = excluded.physical_address,
  copyright_year = excluded.copyright_year;

alter table public.site_settings disable row level security;
